### ISSUE TITLE
如何更新FloatingView里面的内容

### ISSUE THREAD

**Issue by xiamingyu** [hzw1199/FloatingView#1]
super.onAttachedToWindow();
        FloatingViewConfig config = new FloatingViewConfig.Builder()
                .setPaddingLeft(10)
                .setPaddingTop(10)
                .setPaddingRight(10)
                .setPaddingBottom(10)
                .setGravity(FloatingViewConfig.GRAVITY.BOTTOM_CENTER)
                .build();
        floatingView = new FloatingView(this, R.layout.view_floating, config);

layout.view_floating布局里面的空间我没法通过findViewById获取到实例啊，这是不是意味着我完全没法操作里面的view

**Comment by hzw1199** [comment]
@xiamingyu Check release v1.2.0
